---
  title: "ontology"
author: "Dominick J. Lemas"
date: "3/15/2022"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}

library(ontologyIndex)
library(dplyr)
library(tidyverse)

```

```{r setup, include=FALSE}

# https://cran.r-project.org/web/packages/ontologyIndex/vignettes/reading-ontologies.html

doid <- get_ontology("~/r-demo/data/doid.obo")

```

```{r setup, include=FALSE}

ids=c("DOID:0050741","DOID:9270","DOID:13372")


fit=get_term_property(ontology=doid, 
                      property="ancestors", 
                      term="DOID:0080716", 
                      as_names=TRUE)

terms=get_ancestors(doid, c("DOID:0080155"))

minimal <- minimal_set(doid, terms)

roots=c("DOID:655")

exclude_descendants(doid, roots, terms)

prune_descendants(doid, roots, terms)

```

```{r setup, include=FALSE}

# disease
L0=c("DOID:0050117","DOID:7","DOID:14566",
     "DOID:150","DOID:0014667","DOID:630",
     "DOID:0080015","DOID:225")


```